numero = int(input('Digite um numero: '))
print('-' * 12)
print(f'{numero} x 1 = {numero}')
print(f'{numero} x 2 = {numero * 2}')
print(f'{numero} x 2 = {numero * 3}')
print(f'{numero} x 2 = {numero * 4}')
print(f'{numero} x 2 = {numero * 5}')
print(f'{numero} x 2 = {numero * 6}')
print(f'{numero} x 2 = {numero * 7}')
print(f'{numero} x 2 = {numero * 8}')
print(f'{numero} x 2 = {numero * 9}')
print(f'{numero} x 2 = {numero * 10}')
print('-' * 12)